ALTER TABLE fact_vocabulary
    ADD COLUMN IF NOT EXISTS used_in_sentence BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS awaiting_sentence BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS sentence_attempts INTEGER NOT NULL DEFAULT 0;
